[package]
name = "prosic"
version = "2.1.0"
authors = ["Johannes KÃ¶ster <johannes.koester@tu-dortmund.de>"]

[dependencies]
libprosic = { git = "https://github.com/prosic/libprosic.git", branch = "master" }
clap = {version = "2.24", features = ["yaml", "color", "suggestions"]}
rust-htslib = "0.13"
bio = "0.14"
log = "0.3.*"
fern = "0.3.*"
csv = "0.14.*"
itertools = "0.4.*"
time = "*"
rustc-serialize = "0.3.*"
flame = { version = "^0.1.2", optional = true }
flamer = { version = "^0.1.2", optional = true }

[features]
default = []
flame_it = ["flame", "flamer", "libprosic/flame_it"]
